### ISSUE TITLE
Implement other limb darkening laws

### ISSUE THREAD

**Issue by rodluger** [exoplanet-dev/exoplanet#101]
Would it be useful to implement other popular limb darkening laws, such as square root, logarithmic, and the Claret 4-parameter one? See equations 3, 4, and 6 [here](http://articles.adsabs.harvard.edu/pdf/2000A%26A...363.1081C).

It's very straightforward to Taylor expand these functions in terms of polynomials in `mu`. There's virtually no overhead in the conversion from `c, d` and `e, f` to `u` coefficients, since almost everything can be pre-computed. Below are simple implementations for the square root and logarithmic laws. Given a value for the two coefficients, the `get_u` method returns the Taylor expansion coefficients `u` up to order `N`, and calling the class instance returns the intensity at a point or set of points `z` (or, equivalently, `mu`).

Here's the square root law, and below I show a 10th degree approximation:

```python
class SquareRoot(object):
    
    def __init__(self, N, z0=0.5):
        self._N = N
        self._z0 = z0
        self._get_u0()
    
    def _get_u0(self):
        self._u0 = np.zeros(self._N + 1)
        for n in range(self._N + 1):
            fac1 = binom(0.5, n) * self._z0 ** 0.5
            for k in range(n + 1):
                fac2 = binom(n, k) * (-1) ** (n - k) * self._z0 ** -k
                self._u0[k] += fac1 * fac2
    
    def get_u(self, c, d):
        u = d * self._u0
        u[0] += 1 - c - d
        u[1] += c
        return u
    
    def exact(self, z, c, d):
        return 1 - c * (1 - z) - d * (1 - np.sqrt(z))
    
    def __call__(self, z, c, d):
        Z = np.vander(np.atleast_1d(z), self._N + 1, increasing=True)
        return Z.dot(self.get_u(c, d))
```

![image](https://user-images.githubusercontent.com/9323819/84057601-e53dd280-a985-11ea-9594-71f03ce889eb.png)

Here's the same thing for the logarithmic law:

```python
class Logarithmic(object):
    
    def __init__(self, N, z0=0.5):
        self._N = N
        self._z0 = z0
        self._get_u0()
    
    def _get_u0(self):
        self._u0 = np.zeros(self._N + 1)
        self._u0[0] = -self._z0
        self._u0[1] = 1 + np.log(self._z0)
        for n in range(2, self._N + 1):
            fac1 = (-1) ** n * self._z0 / (n * (n - 1))
            for k in range(n + 1):
                fac2 = binom(n, k) * (-1) ** (n - k) * self._z0 ** -k
                self._u0[k] += fac1 * fac2
    
    def get_u(self, e, f):
        u = -f * self._u0
        u[0] += 1 - e
        u[1] += e
        return u
    
    def exact(self, z, e, f):
        return 1 - e * (1 - z) - f * z * np.log(z)
    
    def __call__(self, z, e, f):
        Z = np.vander(np.atleast_1d(z), self._N + 1, increasing=True)
        return Z.dot(self.get_u(e, f))
```

![image](https://user-images.githubusercontent.com/9323819/84057634-f1c22b00-a985-11ea-8cdb-fd598c5569e6.png)

The biggest issue is that the fit is pretty bad at `mu = 0`, right at the limb. This is especially a problem for the square root law, since the derivative is locally infinite. I've chosen to expand both laws around `mu=0.5`, but an even better way to do this is to stitch together a few piecewise expansions centered at different carefully chosen points in `(0, 1]`. Our stellar surface would be composed of a few (say 3) nested disks, which we could model in starry as 3 concentric stars of different radii. The total flux during transit would be a simple linear combination of the flux from each of those. It wouldn't be hard to implement.

What do you think?

**Comment by ericagol** [comment]
This is on of the issues which I raised for the Limbdark project:

https://github.com/rodluger/Limbdark.jl/issues/14

The `\mu=0` behavior of these laws is hard to model with a polynomial (this is also true for the "power-2" law advocated by Maxted).  However, a saving grace is that there is not much of the star at `\mu=0` since `r=\sqrt{1-\mu^2}`.  What I would recommend is to optimize the coefficients of the polynomial when fitting the non-linear law of a transit model (with, say, a radius-ratio of 0.1) rather than for `I(\mu)`.   Then, as you say, the transformation can be held fixed.

I like the idea of stitching together some expansions for stars of different sizes.  I think there will still be an issue near `\mu=0` (`r=1`), but this may be worth giving a go.

**Comment by icweaver** [comment]
Wow, I was just looking for a logarithmic LD implementation in `exoplanet` the other day. Thanks so much for working on this!!

**Comment by ericagol** [comment]
One issue with polynomial limb-darkening laws is that they should guarantee a positive surface-brightness.   This can be accomplished with Sturm's theorem whereby one can check that the boundaries are positive (at the center and edge of the star), and then Sturm's theorem can be checked for the number of roots in between.  If the number of roots in between is zero, then the surface brightness will be positive everywhere.

This could also be used, for example, to guarantee that the limb-darkening is in fact darkening:  i.e. that the surface brightness decreases towards the limb of the star (such as assumed in the reparameterizations by David Kipping).  However, not all wavelengths of physical models are limb-darkened, so this is a more restrictive assumption.  Nevertheless this could also be implemented by using Sturm's theorem applied to the derivative of the specific intensity.

**Comment by dfm** [comment]
I'm going to close this for now. We're going to stick with quadratic models in exoplanet for now, but it would be awesome to play around with this some more in starry!
