### ISSUE TITLE
Can't pickle local object with multi-processing

### ISSUE THREAD

**Issue by darinadaly** [exoplanet-dev/exoplanet#102]
I was able to run the cell with chains=1 but not 4. 
```np.random.seed(23642)
with model:
    trace = xo.sample(
        tune=3500,
        draws=3000,
        start=map_soln,
        chains=1,
        initial_accept=0.8,
        target_accept=0.95,
    )
```
With chains=4, I got `AttributeError: Can't pickle local object 'build_model.<locals>.model_lc'`
How can I work around this without having to wait a long time with chains=1?

**Comment by dfm** [comment]
If you're on Mac, this is the relevant issue: https://github.com/pymc-devs/pymc3/issues/3844
