### ISSUE TITLE
AttributeError: module 'exoplanet' has no attribute 'PyMC3Sampler'

### ISSUE THREAD

**Issue by victoriafoing** [exoplanet-dev/exoplanet#112]
**Describe the bug**

PyMC3Sampler not being recognized in exoplanet

**To Reproduce**
This section should include a simple, standalone code snippet that demonstrates the issue.

The following line of code
sampler = xo.PyMC3Sampler(finish=finish, chains=chains)
returns the error
AttributeError: module 'exoplanet' has no attribute 'PyMC3Sampler'

**Expected behavior**

This worked fine until today

**Your setup (please complete the following information):**
 - Version of exoplanet:
 - Operating system:
 - Python version & installation method (pip, conda, etc.): 

Google Colab

**Additional context**

**Comment by dfm** [comment]
That interface was removed a few versions ago - sorry! The currently recommended interface is described here: https://docs.exoplanet.codes/en/stable/tutorials/pymc3-extras/#dense-mass-matrices

And in the tutorials that follow. Hope this helps!

**Comment by victoriafoing** [comment]
Thanks!
