### ISSUE TITLE
Unable to install exoplanet 0.4

### ISSUE THREAD

**Issue by emilygilbert** [exoplanet-dev/exoplanet#116]
When trying to install exoplanet from source following the instructions for installing from source with `python -m pip install -e .` I get the following error:

    In file included from src/exoplanet/theano_ops/lib/include/exoplanet/starry/ellip.h:21:
    src/exoplanet/theano_ops/lib/include/exoplanet/starry/utils.h:13:10: fatal error: 'Eigen/Core' file not found
    #include <Eigen/Core>
             ^~~~~~~~~~~~
    1 error generated.
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1

@mrtommyb is getting the same error as well

Setup:
 - exoplanet: 0.3.3, but trying to install 0.4
 - MacOS Mojave, 10.14.6
 - Python 3.8.3

**Comment by dfm** [comment]
The git clone needs a `--recursive` flag or you can run

```bash
git submodule init
git submodule update
```

to download the Eigen submodule.

Pull requests welcome to fix the docs :D
