### ISSUE TITLE
Add documentation about multiprocessing gotchas (e.g. fork vs forkserver)

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/exoplanet#121]
Related issues:

- #111 
- #115

**Comment by yanhong-zhao-ef** [comment]
please do - I was trying to have pymc3 models running in python scripts and there was a lot of headache to get it right (I still don't think I have got it right...)

**Comment by dfm** [comment]
@yanhong-zhao-ef: Is this related to exoplanet specifically or PyMC3 more generally?

**Comment by yanhong-zhao-ef** [comment]
oh sorry I thought this is still an issue within pymc3 as I followed the pymc3 issue trail here! I meant pymc3 more generally

**Comment by dfm** [comment]
No worries - it might make sense to post an issue on the PyMC3 GitHub or discourse pages in that case.

**Comment by dfm** [comment]
Re-upping this since @benjaminpope also ran into issues [in his JOSS review](https://github.com/openjournals/joss-reviews/issues/3285#issuecomment-842003491).
