### ISSUE TITLE
SimpleLimbDark doesn't vary u1

### ISSUE THREAD

**Issue by ethankruse** [exoplanet-dev/exoplanet#122]
Hey Dan,

Now that 0.4 is out, I'm trying out your suggestion from our [conversation](https://github.com/rodluger/starry/issues/249#issuecomment-694952462) in starry. It looks like SimpleLimbDark is fast and exactly what I want, but your code example isn't working. `set_u` doesn't seem to care what you feed in as `u1`, the output is always the same. `u2` does have an effect though. Was your example wrong? Any idea what's up?

Here's the example code and outputs I'm getting:

```
import matplotlib.pyplot as plt
import numpy as np
from exoplanet.theano_ops.driver import SimpleLimbDark

plt.figure()
bs = np.arange(-1.5, 1.5, 0.01)
rr = 0.2

u2 = 0.2
for u1 in [0., 0.2, 0.4, 0.6]:
    ld = SimpleLimbDark()
    ld.set_u([u1, u2])
    flux = 1 + ld.apply(bs, rr)
    plt.plot(bs, flux, label=f'u1 = {u1}, u2 = {u2}')
plt.legend()


plt.figure()

u1 = 0.2
for u2 in [0., 0.2, 0.4, 0.6]:
    ld = SimpleLimbDark()
    ld.set_u([u1, u2])
    flux = 1 + ld.apply(bs, rr)
    plt.plot(bs, flux, label=f'u1 = {u1}, u2 = {u2}')
plt.legend()
```

![Figure_1](https://user-images.githubusercontent.com/6944089/97359684-836a0080-1873-11eb-8d3a-09b2f55e639e.png)
![Figure_2](https://user-images.githubusercontent.com/6944089/97359683-836a0080-1873-11eb-9330-4f4c0975f2c8.png)

**Comment by dfm** [comment]
Good catch! I think that what you want is `set_u([1, u1, u2])` for now, but let me do a few tests. It's related to the definitions from the limbdark paper.

**Comment by dfm** [comment]
I can confirm that this works. [In the main code base](https://github.com/exoplanet-dev/exoplanet/blob/main/src/exoplanet/light_curves/limb_dark.py#L28), it actually is defined as `[-1, u1, u2]` but I think that since it gets normalized the actual value of the first entry does not enter (it would only matter for the baseline in the more general starry case, I think). It would be good to update this op to automatically add the `-1` so that the behavior is as expected.

**Comment by ericagol** [comment]
Yes, that looks correct:  just after equation (2) in the paper, it states that `u_0 = -1`.  
<img width="442" alt="limbdark_definitions" src="https://user-images.githubusercontent.com/243664/97395132-76fc9c80-18a1-11eb-9409-5c3dd3fc5e94.png">

**Comment by rodluger** [comment]
@dfm @ethankruse Is this method now working? Do you need my help with anything?

**Comment by ethankruse** [comment]
Yep, my tests are passing and it seems to be working once I add in the -1 as the first parameter.
