### ISSUE TITLE
Error in radial velocity for `t~p`, `omega=0.5*pi`

### ISSUE THREAD

**Issue by rodluger** [exoplanet-dev/exoplanet#145]
**Describe the bug**
The radial velocity returned by `exoplanet.orbits.KeplerianOrbit().get_radial_velocity(t)` jumps discontinuously when `t` is very close to `t0 + period`. 

A few things I've observed:

- This seems to happen only when the argument of pericenter `omega=0.5*pi` (exactly; changing this by as little as `1e-15` fixes the error). 
- Setting `ecc=None` also fixes the issue. However, setting it to zero or *any* nonzero value causes the issue to appear.
- The discontinuity occurs for `|t - (t0 + period)| < 1e-13`. 
- This only seems to happen for some specific orbital periods. For instance, `365.25` causes the error, by `365.24` does not. `360.00` causes the error, but `100.00` does not. I haven't been able to find a pattern.

**To Reproduce**
```python
import numpy as np
import matplotlib.pyplot as plt
import exoplanet as xo

period = 365.25

orbit = xo.orbits.KeplerianOrbit(
    period=period,
    t0=0.0,
    incl=0.5 * np.pi,
    ecc=0.0,
    omega=0.5* np.pi,
    m_planet=3e-06,
    m_star=1.0,
    r_star=1.0,
)

t = np.linspace(0, period, 1000)
rv = orbit.get_radial_velocity(t=t).eval()
plt.plot(t, rv)
plt.xlabel("t [days]")
plt.ylabel("rv [m/s]");
```

The above code produces the following plot, where the discontinuity is evident at `365.25` days. The RV at that time should be zero, but it's equal to `-0.06383679`.

![image](https://user-images.githubusercontent.com/9323819/109011970-7b826780-767f-11eb-9eb0-e255c5e096cc.png)

The sensitivity of `1e-13` can be seen in this figure:

```python
delta = np.logspace(-15, -12, 1000)
rv = orbit.get_radial_velocity(t=period + delta).eval()
plt.plot(np.log10(delta), rv)
plt.xlabel("log |t - p|")
plt.ylabel("rv [m/s]");
```

![image](https://user-images.githubusercontent.com/9323819/109012675-462a4980-7680-11eb-8af9-4feec72be7d6.png)

**Expected behavior**
For `omega = 0.5 * np.pi`, the RV at `t = t0 + p` should be exactly zero.

**Your setup (please complete the following information):**
 - Version of exoplanet: `0.4.4`
 - Operating system: MacOS Catalina
 - Python version & installation method (pip, conda, etc.): Conda Python 3.8

**Additional context**
This issue is unlikely to be encountered in practice because it happens at a pathological point. But that point (`omega=0.5 * np.pi`) is the default in `starry`, so I'm getting this discontinuity in several of my tutorial notebooks. If you're swamped I can try to dig into the Kepler solver code and see if I can find anything.

**Comment by dfm** [comment]
Thanks - all this info is super useful to track down the issue. I bet it has something to do with numerical issues the mod implementation in the kepler solver. I'll get it sorted!

**Comment by ericagol** [comment]
What is the behavior if you do not set the eccentricity?  The Kepler solver shouldn't be needed for `e=0`, and it looks like the code should work fine for `ecc=None`:    https://github.com/exoplanet-dev/exoplanet/blob/55d2252c71191044613fabb9c8bd3062aca3bc1b/src/exoplanet/orbits/keplerian.py#L188-L191

**Comment by rodluger** [comment]
Yep, it works fine with `ecc=None`.
