### ISSUE TITLE
`SimpleTransitOrbit` transit shape is not consistent with `KeplerianOrbit` transit shape

### ISSUE THREAD

**Issue by christinahedges** [exoplanet-dev/exoplanet#147]
**Describe the bug**
The `SimpleTransitOrbit` class I believe can make transit shapes, without enforcing Kepler's laws. When using it, it wasn't behaving as expected. When I set `period`, `t0`, `b` and `duration` to the same values, the transit shapes are very different.

**To Reproduce**
Please see https://gist.github.com/christinahedges/ea3ad229e82fded715794be65124695f

**Expected behavior**
I believe if I set `period`, `t0`, `b` and `duration` to the same value, and have `b` < `r_star - 2*r` I should have the same transit shape.

**Your setup (please complete the following information):**
 - Version of exoplanet: `0.4.5.dev2+g55d2252`
 - Operating system: macOS (catalina)
 - Python version & installation method (pip, conda, etc.): 3.6.7 (conda)

**Comment by dfm** [comment]
It looks like this is the issue:

https://github.com/exoplanet-dev/exoplanet/blob/16cc4ef38258573e6a7f3fb4017c12f2fc19cbe7/src/exoplanet/orbits/simple.py#L64

We should refactor the `SimpleTransitOrbit` to take `r_planet` as a parameter and re-define the duration properly as the beginning of ingress to end of egress.
