### ISSUE TITLE
Inconsistent values returned for semi-major axis in KeplerianOrbit

### ISSUE THREAD

**Issue by icweaver** [exoplanet-dev/exoplanet#149]
**Describe the bug**
`KeplerianOrbit` seems to return a / r_star instead of a when passed the stellar density instead of m_star and r_star separately.

**To Reproduce**
```python
import numpy as np

from exoplanet.orbits.keplerian import KeplerianOrbit
from batman import _rsky

m_star = 0.151
r_star = 0.189
period = 0.4626413
t0 = 0.2
b = 0.5
ecc = 0.1
omega = 0.1
t = np.linspace(0, period, 500)

orbit = KeplerianOrbit(
    r_star=r_star,
    m_star=m_star,
    period=period,
    t0=t0,
    b=b,
    ecc=ecc,
    omega=omega,
)
orbit.a.eval() # 1.34047805 (solar radii)
orbit.rho_star.eval() # 31.53136891 (g/cc)

orbit2 = KeplerianOrbit(
    rho_star = 31.53136891307936,
    period=period,
    t0=t0,
    b=b,
    ecc=ecc,
    omega=omega,
)
orbit2.a.eval() # 7.09247644 # I think this is actually a/R_star now
orbit2.rho_star.eval() # 31.53136891

# Quick check
import astropy.units as u
orbit.a.eval() * u.Rsun / orbit.r_star.eval() # <Quantity 7.09247644 solRad>
orbit2.a.eval() * u.Rsun / orbit2.r_star.eval() # <Quantity 7.09247644 solRad>
```

**Expected behavior**
```python
orbit2.a.eval() # 1.34047805
```

**Your setup (please complete the following information):**
 - Version of exoplanet: 0.3.3 | pyh9f0ad1d_0 | conda-forge
 - Operating system: Linux Mint 20.1 x86_64
 - Python version & installation method (pip, conda, etc.): Python 3.6.13 | conda 4.9.2

**Additional context**
I noticed this when trying out different inputs for the test [here](https://github.com/exoplanet-dev/exoplanet/blob/main/tests/orbits/keplerian_test.py#L316-L349)

**Comment by dfm** [comment]
This is the expected behavior because the default R_star is 1.0. How would you want it to set the units if R_star and M_star are not provided?

**Comment by icweaver** [comment]
Hi Dan, thanks for getting back to me so quickly. I didn't realize that I was implicitly keeping r_star fixed to the value in the first example when trying testing this out. I see now that defaulting to 1 solar radii by default is explicitly outlined in the documentation, sorry for the noise!
