### ISSUE TITLE
RV-multi tutorial is not working anymore (Jupyter notebook)

### ISSUE THREAD

**Issue by LucaNap** [exoplanet-dev/exoplanet#153]
I noticed that the [RV multi tutorial](https://gallery.exoplanet.codes/en/latest/tutorials/rv-multi/) is not working anymore, even in Jupyter notebook.
The following error shows up after pmx.sample has been called: 

AttributeError: Can't get attribute 'rv_model' on <module '__main__' (built-in)>

I noticed that using the argument _pickle_backend='dill'_ I can get the sample running but even so I am unable to get the results as if the sampling had been interrupted at some point. By the way I am referring to the tutorial because it's easier, but I first had this issue with some data of mine that I was trying to fit, but no matter how general or easy to fit the data is, I always get the same issue. Is there a way to circumvent this error? Thank you!

**Setup**
 - Version of exoplanet: latest
 - Operating system: Windows 10
 - Python version & installation method: Conda, latest

**Comment by dfm** [comment]
This tutorial runs just fine on Mac and Ubuntu (which are the two platforms that I develop on) so this is probably something to do with Windows and/or your specific setup. You could try changing the multiprocessing context parameter (perhaps fork vs forkserver) but I can't give too many tips since I don't often use Windows.

**Comment by dfm** [comment]
This is how I set it on Mac: https://github.com/exoplanet-dev/case-studies/blob/1e2b78e75b6617ad97a9e8a86cdf088d712c1f27/docs/tutorials/notebook_setup.py#L24

but you should also be able to use the `mp_ctx="fork"` parameter for `sample` directly.

**Comment by LucaNap** [comment]
Thank you! Unfortunately _mp_ctx='fork'_  or forkserver is not working either..

ValueError: cannot find context for 'fork'

https://github.com/lyft/l5kit/issues/129 maybe fork is only available on macos?

**Comment by dfm** [comment]
Yes - that looks right: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

When you say this doesn't work "anymore" when did you have it working before? This behavior shouldn't have changed in the v0.4 stream. I'll try to give this a shot on windows at some point to see if I can figure out a workaround.

**Comment by LucaNap** [comment]
Sorry @dfm , I was able to get the tutorial working in Windows10 by using the argument _pickle_backend='dill'_, contrary to what I have said in the opening post! Apparently the process did finish, I just made a mistake trying to call the results. But I guess this post will be useful to Windows user who have had the same issue..

**Comment by dfm** [comment]
Great news! Glad you got it working.

Again it *does* work: those tutorials are automatically generated by *executing the code*. So while there might be issues when you try to run it, the conclusion is not that it "doesn't work", but instead that there's an issue with your setup :D. In this case you'll probably need to update corner.
