### ISSUE TITLE
Missing citation and/or wrong tag in get_citations_for_model()

### ISSUE THREAD

**Issue by elnjensen** [exoplanet-dev/exoplanet#157]
The output of `get_citations_for_model()` includes the text "This research made use of \textsf{exoplanet} \citep{exoplanet} and its dependencies" but the accompanying BibTeX code lists no citation with the label "exoplanet".  I'm guessing this is supposed to be "exoplanet:exoplanet"?   If so, then that tag could also be removed from the parenthetical list of dependencies (and if not, then there's a missing reference in the BibTeX output).

**Comment by dfm** [comment]
Thanks for catching this! I suggest a fix over in #158

**Comment by rodluger** [comment]
It would also be useful to have it cite the exoplanet paper as well...

![bean](https://user-images.githubusercontent.com/9323819/113714626-98667d80-96b6-11eb-8241-331a3e598df5.gif)

**Comment by dfm** [comment]
GET OUTTA HERE @rodluger!!
