### ISSUE TITLE
Samples projected to run over 19 hours.

### ISSUE THREAD

**Issue by JosephKarpinski** [exoplanet-dev/exoplanet#183]
multiple samples are projected to run over 19 hours:
A quick intro to PyMC3 for exoplaneteers
Radial velocity fitting

On iMac with 4 cores, runningMacOS Big Sur 

Tried unsuccessfully:

import multiprocessing as mp 
mp.set_start_method("fork")

Smaller tune and/or draw parameters?

<img width="1352" alt="Screen Shot 2021-05-06 at 4 52 48 PM" src="https://user-images.githubusercontent.com/37123616/117368207-32c20880-ae91-11eb-8580-1d7404eef74a.png">
<img width="1352" alt="Screen Shot 2021-05-06 at 4 58 52 PM" src="https://user-images.githubusercontent.com/37123616/117368238-3d7c9d80-ae91-11eb-8604-0db2dc66c13a.png">

**Comment by dfm** [comment]
Did you also try `cores=1` as I suggested on Twitter?

**Comment by JosephKarpinski** [comment]
Yes,

Changing codes=2 to cores=1, had no impact.
With Radial Velocity example: 27/8000 projected to run 12:49:48 plus

**Comment by JosephKarpinski** [comment]
Example:

<img width="1702" alt="Screen Shot 2021-05-06 at 6 11 29 PM" src="https://user-images.githubusercontent.com/37123616/117371858-9d297780-ae96-11eb-9bc3-88053977c8ae.png">

**Comment by JosephKarpinski** [comment]
Additional documentation

pip3 install aas-timeseries
Collecting aas-timeseries
  Downloading aas_timeseries-0.1b4-py2.py3-none-any.whl (419 kB)
     |████████████████████████████████| 419 kB 2.6 MB/s 
Collecting palettable
  Downloading palettable-3.3.0-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 4.6 MB/s 
Requirement already satisfied: matplotlib in ./opt/anaconda3/lib/python3.8/site-packages (from aas-timeseries) (3.4.1)
Requirement already satisfied: astropy in ./opt/anaconda3/lib/python3.8/site-packages (from aas-timeseries) (4.2.1)
Collecting jupyter-aas-timeseries
  Downloading jupyter_aas_timeseries-0.1.7-py2.py3-none-any.whl (703 kB)
     |████████████████████████████████| 703 kB 3.7 MB/s 
Requirement already satisfied: traitlets in ./opt/anaconda3/lib/python3.8/site-packages (from aas-timeseries) (5.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (2.4.7)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (8.2.0)
Requirement already satisfied: numpy>=1.16 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->aas-timeseries) (1.20.2)
Requirement already satisfied: pyerfa in ./opt/anaconda3/lib/python3.8/site-packages (from astropy->aas-timeseries) (1.7.2)
Requirement already satisfied: ipywidgets>=7.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jupyter-aas-timeseries->aas-timeseries) (7.6.3)
Requirement already satisfied: ipython-genutils in ./opt/anaconda3/lib/python3.8/site-packages (from traitlets->aas-timeseries) (0.2.0)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->aas-timeseries) (1.15.0)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (7.19.0)
Requirement already satisfied: ipykernel>=4.5.1 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (5.3.4)
Requirement already satisfied: nbformat>=4.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (5.0.8)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (3.5.1)
Requirement already satisfied: setuptools>=18.5 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (56.0.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.1.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (3.0.8)
Requirement already satisfied: pickleshare in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.7.5)
Requirement already satisfied: decorator in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (4.4.2)
Requirement already satisfied: pygments in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (2.7.2)
Requirement already satisfied: backcall in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.2.0)
Requirement already satisfied: jedi>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.17.1)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (4.8.0)
Requirement already satisfied: tornado>=4.2 in ./opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (6.0.4)
Requirement already satisfied: jupyter-client in ./opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (6.1.7)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (3.2.0)
Requirement already satisfied: jupyter-core in ./opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (4.6.3)
Requirement already satisfied: notebook>=4.4.1 in ./opt/anaconda3/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (6.1.4)
Requirement already satisfied: wcwidth in ./opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.6.0)
Requirement already satisfied: pyzmq>=13 in ./opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (19.0.2)
Requirement already satisfied: attrs>=17.4.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.17.3)
Requirement already satisfied: jinja2 in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (2.11.2)
Requirement already satisfied: prometheus-client in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.8.0)
Requirement already satisfied: nbconvert in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (6.0.7)
Requirement already satisfied: terminado>=0.8.3 in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.9.1)
Requirement already satisfied: Send2Trash in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.5.0)
Requirement already satisfied: argon2-cffi in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (20.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./opt/anaconda3/lib/python3.8/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.1.1)
Requirement already satisfied: jupyterlab-pygments in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.1.2)
Requirement already satisfied: testpath in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.5.1)
Requirement already satisfied: pandocfilters>=1.4.1 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.4.3)
Requirement already satisfied: defusedxml in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.6.0)
Requirement already satisfied: bleach in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (3.2.1)
Requirement already satisfied: entrypoints>=0.2.2 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.3)
Requirement already satisfied: cffi>=1.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.14.3)
Requirement already satisfied: async-generator in ./opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.10)
Requirement already satisfied: nest-asyncio in ./opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (1.4.2)
Requirement already satisfied: webencodings in ./opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (0.5.1)
Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (20.4)
Requirement already satisfied: pycparser in ./opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->jupyter-aas-timeseries->aas-timeseries) (2.20)
Installing collected packages: palettable, jupyter-aas-timeseries, aas-timeseries
Successfully installed aas-timeseries-0.1b4 jupyter-aas-timeseries-0.1.7 palettable-3.3.0
(base) josephkarpinski@Josephs-iMac ~ % pip3 install -U exoplanet
Collecting exoplanet
  Downloading exoplanet-0.5.0-py3-none-any.whl (39 kB)
Collecting exoplanet-core>=0.1
  Downloading exoplanet_core-0.1.1-cp38-cp38-macosx_10_9_x86_64.whl (142 kB)
     |████████████████████████████████| 142 kB 4.9 MB/s 
Requirement already satisfied, skipping upgrade: pymc3>=3.9 in ./opt/anaconda3/lib/python3.8/site-packages (from exoplanet) (3.11.2)
Collecting aesara-theano-fallback>=0.0.2
  Downloading aesara_theano_fallback-0.0.4-py3-none-any.whl (5.4 kB)
Requirement already satisfied, skipping upgrade: astropy>=3.1 in ./opt/anaconda3/lib/python3.8/site-packages (from exoplanet) (4.2.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.0 in ./opt/anaconda3/lib/python3.8/site-packages (from exoplanet-core>=0.1->exoplanet) (1.20.2)
Requirement already satisfied, skipping upgrade: arviz>=0.11.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (0.11.2)
Requirement already satisfied, skipping upgrade: dill in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (0.3.3)
Requirement already satisfied, skipping upgrade: theano-pymc==1.1.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (1.1.2)
Requirement already satisfied, skipping upgrade: semver in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (2.13.0)
Requirement already satisfied, skipping upgrade: scipy>=1.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (1.6.2)
Requirement already satisfied, skipping upgrade: fastprogress>=0.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (1.0.0)
Requirement already satisfied, skipping upgrade: patsy>=0.5.1 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (0.5.1)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (3.7.4.3)
Requirement already satisfied, skipping upgrade: cachetools>=4.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (4.2.1)
Requirement already satisfied, skipping upgrade: pandas>=0.24.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->exoplanet) (1.2.4)
Requirement already satisfied, skipping upgrade: pyerfa in ./opt/anaconda3/lib/python3.8/site-packages (from astropy>=3.1->exoplanet) (1.7.2)
Requirement already satisfied, skipping upgrade: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->exoplanet) (20.4)
Requirement already satisfied, skipping upgrade: matplotlib>=3.0 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->exoplanet) (3.4.1)
Requirement already satisfied, skipping upgrade: netcdf4 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->exoplanet) (1.5.6)
Requirement already satisfied, skipping upgrade: setuptools>=38.4 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->exoplanet) (56.0.0)
Requirement already satisfied, skipping upgrade: xarray>=0.16.1 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->exoplanet) (0.17.0)
Requirement already satisfied, skipping upgrade: filelock in ./opt/anaconda3/lib/python3.8/site-packages (from theano-pymc==1.1.2->pymc3>=3.9->exoplanet) (3.0.12)
Requirement already satisfied, skipping upgrade: six in ./opt/anaconda3/lib/python3.8/site-packages (from patsy>=0.5.1->pymc3>=3.9->exoplanet) (1.15.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.0->pymc3>=3.9->exoplanet) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.0->pymc3>=3.9->exoplanet) (2021.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from packaging->arviz>=0.11.0->pymc3>=3.9->exoplanet) (2.4.7)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->exoplanet) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->exoplanet) (1.3.1)
Requirement already satisfied, skipping upgrade: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->exoplanet) (8.2.0)
Requirement already satisfied, skipping upgrade: cftime in ./opt/anaconda3/lib/python3.8/site-packages (from netcdf4->arviz>=0.11.0->pymc3>=3.9->exoplanet) (1.4.1)
Installing collected packages: exoplanet-core, aesara-theano-fallback, exoplanet
Successfully installed aesara-theano-fallback-0.0.4 exoplanet-0.5.0 exoplanet-core-0.1.1
(base) josephkarpinski@Josephs-iMac ~ % pip3 install pymc3_ext
Collecting pymc3_ext
  Downloading pymc3_ext-0.1.0-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: aesara-theano-fallback>=0.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3_ext) (0.0.4)
Requirement already satisfied: pymc3>=3.9 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3_ext) (3.11.2)
Requirement already satisfied: arviz>=0.11.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (0.11.2)
Requirement already satisfied: patsy>=0.5.1 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (0.5.1)
Requirement already satisfied: theano-pymc==1.1.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (1.1.2)
Requirement already satisfied: semver in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (2.13.0)
Requirement already satisfied: scipy>=1.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (1.6.2)
Requirement already satisfied: pandas>=0.24.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (1.2.4)
Requirement already satisfied: typing-extensions>=3.7.4 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (3.7.4.3)
Requirement already satisfied: numpy>=1.15.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (1.20.2)
Requirement already satisfied: cachetools>=4.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (4.2.1)
Requirement already satisfied: fastprogress>=0.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (1.0.0)
Requirement already satisfied: dill in ./opt/anaconda3/lib/python3.8/site-packages (from pymc3>=3.9->pymc3_ext) (0.3.3)
Requirement already satisfied: setuptools>=38.4 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (56.0.0)
Requirement already satisfied: xarray>=0.16.1 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (0.17.0)
Requirement already satisfied: netcdf4 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (1.5.6)
Requirement already satisfied: matplotlib>=3.0 in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (3.4.1)
Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (20.4)
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.8/site-packages (from patsy>=0.5.1->pymc3>=3.9->pymc3_ext) (1.15.0)
Requirement already satisfied: filelock in ./opt/anaconda3/lib/python3.8/site-packages (from theano-pymc==1.1.2->pymc3>=3.9->pymc3_ext) (3.0.12)
Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.0->pymc3>=3.9->pymc3_ext) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.0->pymc3>=3.9->pymc3_ext) (2021.1)
Requirement already satisfied: cftime in ./opt/anaconda3/lib/python3.8/site-packages (from netcdf4->arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (1.4.1)
Requirement already satisfied: pyparsing>=2.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (2.4.7)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (8.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0->arviz>=0.11.0->pymc3>=3.9->pymc3_ext) (1.3.1)
Installing collected packages: pymc3-ext
Successfully installed pymc3-ext-0.1.0

**Comment by JosephKarpinski** [comment]
Solved it.

Installation of Xcode and accepting the agreement fixed the problem:

![IMG_7398](https://user-images.githubusercontent.com/37123616/117387488-fef9d980-aeb6-11eb-876a-fb494ebf4682.jpg)

<img width="1357" alt="Screen Shot 2021-05-06 at 9 58 25 PM" src="https://user-images.githubusercontent.com/37123616/117387519-09b46e80-aeb7-11eb-9741-dd65f48a29ba.png">

<img width="1302" alt="RV Good" src="https://user-images.githubusercontent.com/37123616/117387550-133dd680-aeb7-11eb-85f2-a755cef03cd6.png">
