### ISSUE TITLE
JOSS Review: Installation

### ISSUE THREAD

**Issue by grburgess** [exoplanet-dev/exoplanet#191]
The pip install proceeds just fine, but there are some issues when installing the tests which seem to be related to this:

https://github.com/lkreidberg/batman/issues/48

This is likely a transient (no pun intended) issue, and only affect the following tests:

```
======================================================================== short test summary info =========================================================================
FAILED tests/light_curves_test.py::test_small_star - ModuleNotFoundError: No module named 'batman'
FAILED tests/orbits/keplerian_test.py::test_sky_coords - ModuleNotFoundError: No module named 'batman'
FAILED tests/orbits/keplerian_test.py::test_small_star - ModuleNotFoundError: No module named 'batman'
```

Thus, it is not related to exoplanet and is only a heads-up.

**Comment by grburgess** [comment]
https://github.com/openjournals/joss-reviews/issues/3285#

**Comment by dfm** [comment]
In `https://github.com/exoplanet-dev/exoplanet/pull/186` batman is made an optional dependency for the tests, but can you confirm that you installed the `test` extras e.g.:

```python
pip install ".[test]"
```

and that worked?

Did you find that you can't install `batman` in isolation anyways? If so, I'll submit a PR over there too :D

**Comment by grburgess** [comment]
Exactly, the error came because I did:
```pip install ".[test]"``` 

and then I went down a rabbit hole wondering why my OMP was not being picked up. But it turns out that there is the above issue. Thus, everything worked except ```batman``` . I guess they are using the George Clooney version at the moment.

**Comment by dfm** [comment]
@grburgess: Thanks for the confirmation!

**Comment by dfm** [comment]
It looks like https://github.com/lkreidberg/batman/issues/48 was fixed and batman is now only an optional dependency for the tests so I'm going to close this. Thanks!
