### ISSUE TITLE
AttributeError: module 'exoplanet' has no attribute 'gp'

### ISSUE THREAD

**Issue by pgorrini** [exoplanet-dev/exoplanet#223]
Hello,

I'm trying to use the **specgp** package (which uses **exoplanet**) and when running

```
import exoplanet as xo
term = xo.gp.terms.SHOTerm(log_S0=0.0, log_w0=1.0, log_Q=-np.log(np.sqrt(2)))
```

I get the following error: 

`AttributeError: module 'exoplanet' has no attribute 'gp'`

I'm using the latest version of **exoplanet** (0.5.2)

**Comment by tagordon** [comment]
Hi @pgorrini, the latest version of exoplanet no longer includes the gp module. Specgp should be compatible with the last version of exoplanet that did include that module. Alternatively, the same functionality has been implemented in celerite2 under the “kron” branch (but I don’t believe it’s in the current release).

**Comment by dfm** [comment]
Yeah - I'm sorry about the shifting infrastructure! I'm hoping that we can have similar functionality in `celerite2`, but I've been slow to get it implemented. To downgrade `exoplanet`, [it looks like](https://docs.exoplanet.codes/en/latest/changes/#id19) you'll need version `<0.4`.

**Comment by pgorrini** [comment]
Ok yes, with an oldest `exoplanet`version it work well. Thanks!
