### ISSUE TITLE
Add notes about reparameterization to the docs

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/exoplanet#24]

**Comment by dfm** [comment]
+1 reminder on this. @petigura has notes.

**Comment by ericagol** [comment]
I have had some issues with severe numerical cancellations for the derivatives which occur in my N-body code (and even are present when N=2, i.e. in the Keplerian case).  Have you checked that the auto diff derivatives are accurate?

Eric Agol
Astronomy Professor
University of Washington

**Comment by ericagol** [comment]
The reason I bring this up is that the cancellations can depend on the parameterization.

Eric Agol
Astronomy Professor
University of Washington

**Comment by dfm** [comment]
All the derivatives are pretty extensively tested. That's not the issue. The problem is normally variable dynamic range (see Neal's funnel etc.)

**Comment by dfm** [comment]
Also called out by @grburgess in https://github.com/openjournals/joss-reviews/issues/3285:

> I noticed that one of the models was an interpolated light curve. Is this actually used in fitting? If it is used as a template where the shape does not change except for the scaling, this should be fine. But HMC typically goes bonkers with interpolated models that change their shape. This is more of curiosity of mine... but I also may have not understood what that model is used for in the library.

**Comment by ericagol** [comment]
Which portion of the model is this referring to?

**Comment by dfm** [comment]
@ericagol: Whoops - that was the wrong quote! Updated.
