### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by ethankruse** [exoplanet-dev/exoplanet#245]
It's a new year, I decided to try to check out Python 3.10. Of everything I routinely use, it looks like exoplanet and spyder are the only 2 that don't have a 3.10-compatible version out yet. Looks like Dan (or someone) got it working for emcee and celerite, so I'm wondering if exoplanet is somewhere on the todo list. 

I'm not in a horrible hurry to fully upgrade, so don't rush, but wanted to put it on the radar or see what the timeline might be.

**Comment by dfm** [comment]
Good questions! I wouldn't expect any roadblocks so should be quick. This week is insane to me, but I'll try to mint a new release early next week and report back here if I find any problems.

**Comment by dfm** [comment]
I've released updated versions of `aesara-theano-fallback` and `exoplanet-core` with support for Python 3.10 and the beta PyMC v4: https://github.com/exoplanet-dev/exoplanet-core/releases/tag/v0.2.0rc1

Tomorrow on to `exoplanet` and `celerite2`!
