### ISSUE TITLE
Can Exoplanet/Pymc3 interact with TTVFaster? 

### ISSUE THREAD

**Issue by asmasca** [exoplanet-dev/exoplanet#252]
Hi Dan, I'm Alejandro Suárez Mascareño, we spoke at the Oxford GPRV workshop. 

Yesterday I started playing around with Exoplanet/Pymc3 following your recommendation. First of all I want to say I'm impressed about how efficient it is, and how convenient lots of the functions are. Thanks for pointing me here. 

I tried to move a likelihood designed for Dynesty/Emcee into Exoplanet, that includes a call to the python interface of TTVFaster (1). I found out that TTVFaster really doesn't like the objects created by pymc3. Do you know if there's a way to make them interact nicely? Or an alternative that can be used? 

I know I can always sample directly the times of transits (as in the tutorial), and then compute the masses later, but I wanted to sample the planetary parameters directly into the model to fit activity, transits and RV simultaneously. 

(1)https://github.com/ericagol/TTVFaster/tree/master/Python

Thanks in advance

**Comment by ericagol** [comment]
Yes, they are fairly straightforward.  The most complicated part is computing the Laplace integrals.

**Comment by asmasca** [comment]
Ok, that sounds like a thing I might be tempted to try.  Is the python code (ttvfaster.py) fully functional? or would it be better to continue using the C version (as called by _ttvfaster.pyx).
