### ISSUE TITLE
AttributeError: module 'exoplanet' has no attribute 'get_dense_nuts_step'

### ISSUE THREAD

**Issue by sukanyaX** [exoplanet-dev/exoplanet#268]
In trying to run The Joker, I encountered this error, specifically in this code snippet when I try to make the corner plot - 

trace = pm.sample(
        tune=500, draws=1000,
        start=mcmc_init,
        step=xo.get_dense_nuts_step(target_accept=0.95),
        random_seed=seed,
        cores=1, chains=2)  

 - Version of exoplanet:  0.5.2
 - Operating system: Mac OS Big Sur 11.2.2
 - python 3.9.6, installed via pip. 

Thanks for your help!

**Comment by dfm** [comment]
That method has long been deprecated. Depending on the version of PyMC3 that you're using, you can use `init="adapt_full"` instead of `step=`, or the `sample` function from https://github.com/exoplanet-dev/pymc3-ext (without the `step` argument... everything else should work)

Hope this helps!
