### ISSUE TITLE
Including Relativistic effects in exoplanet?

### ISSUE THREAD

**Issue by ericagol** [exoplanet-dev/exoplanet#54]
The new Sgr A*/S02 paper on GR effects made me wonder if it would be worthwhile to include relativistic effects in exoplanet:

https://science.sciencemag.org/content/early/2019/07/24/science.aav8137

It's also interesting to note that they used the STAN implementation of NUTS as a check on their results.

**Comment by arjunsavel** [comment]
Hello! I was wondering if it'd be desirable to implement this by introducing post-Newtonian corrections with REBOUNDx (example [here](https://github.com/dtamayo/reboundx/blob/master/ipython_examples/GeneralRelativity.ipynb?fbclid=IwAR3w0BBqi6d07hJM6KZeAQ-UfGIOQhnUek4sNFxHlFyDN2lLfkA_FRwEGHo)).

**Comment by dfm** [comment]
@arjunsavel That would definitely be interesting! I've implemented an interface to rebound (without the x) and an extension to include this would be cool, but I don't have a sense of how feasible that would be (does REBOUNDx play nice with variations for example?). Either way, if you're interested in taking a stab at it, that would be awesome! Take a look [here](https://github.com/exoplanet-dev/exoplanet/blob/master/src/exoplanet/theano_ops/rebound/rebound.py) for the custom Theano op that does the N-body integration and propagates derivatives using Python (there's [also a faster version that uses the C-API directly](https://github.com/dfm/rebound-pymc3), but it's probably better to start with Python) and [here](https://github.com/exoplanet-dev/exoplanet/blob/master/src/exoplanet/orbits/rebound.py) for where that gets a more "user-friendly" orbit interface. It's not super well commented, but I'm happy to chat if you're interested.

**Comment by arjunsavel** [comment]
@dfm Thanks for the response! I'd been thinking of making a PR to `rebound-pymc3`, but I agree that starting with the Python implementation would make sense. Also, I'm not sure whether REBOUNDx handles variations — I'll definitely give it a go, though!

**Comment by dfm** [comment]
Closed by #133
