### ISSUE TITLE
Help with program

### ISSUE THREAD

**Issue by hughesymendes** [exoplanet-dev/exoplanet#74]
Hi everyone, 

My name is Alex and im an undergraduate student at Loughborough university, currently undergoing my final year project in which im using data from TESS to hunt for my own exoplanet candidates. 

Im trying to use radial velocities to help calculate masses, in order to negate eclipsing binaries from my shortlist etc but il admit my coding is sub par and im not sure how to go about it, however i was pointed in the direction of your program! 

Im using TESS target pixel files and have created lightcurves that include all flux and time metadata, but where do you find values for radial velocities such that i can create a radial velocity plot? Is it something that i calculate using my flux values or do you go to an archive somewhere that has dedicated RV values?

Sorry about the probably face palm stupid question!  I appreciate any help that can be given to steer me in the right direction towards calculating orbiting masses. 

Many thanks
Alex

**Comment by dfm** [comment]
TESS does not measure radial velocities so you'll need to rely on another instrument. The NASA Exoplanet Archive has some public RV measurements and you can sometimes find values in tables published about specific targets. Most planets discovered in TESS will not have RV follow-up unfortunately.
