### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/exoplanet#8]
Paging @rodluger and @megbedell

**Comment by dfm** [comment]
This is all I've got so far:

![exoplanet-logo](https://user-images.githubusercontent.com/350282/49122860-44486480-f284-11e8-8758-42e1416e7840.png)

@ruthangus says it's crap so I need your help @rodluger and @megbedell!!!

**Comment by RuthAngus** [comment]
I didn't say it was crap I said it wasn't distinctive enough!

**Comment by danielhey** [comment]
no need to thank me

![lol](https://user-images.githubusercontent.com/38233719/49638524-8a5bb000-fa5c-11e8-8268-3d891247fda5.PNG)

**Comment by dfm** [comment]
hahaha! Thank you both. I think we'll stick with no logo for now and revisit this eventually.
