### ISSUE TITLE
Combining different datasets

### ISSUE THREAD

**Issue by shbhuk** [exoplanet-dev/exoplanet#82]
Hi,
I am trying to combine different photometric datasets first for transit modelling, and eventually combine later with RVs for a joint fit. 

I'm wondering regarding the best way to do this such that the log likelihoods take into account different sample sizes? For example, if I'm combining a TESS light curve with 2-3 ground based transits,  due to the larger sample size of the TESS sample (than the ground based observations) it would contribute more to the parameter estimation via log likelihood minimization. 

Do we need to weight the individual instrument log likelihoods to account for differing sample sizes (in the limiting case of similar measurement errors).

**Comment by dfm** [comment]
You should never reweight datasets based on the number of observations. The only correct way to combine datasets is to multiply the likelihoods! If you believe that a dataset is overly constraining then that means that you don't believe the error bars. In that case you deal with it by making the noise model more flexible by fitting for a jitter or by using a Gaussian process.

**Comment by shbhuk** [comment]
I see. So, in the case study for combining RVs and photometry is the log likelihood addition being handled implicitly behind the scenes by PyMC3?

**Comment by dfm** [comment]
Yep - that's right!

**Comment by shbhuk** [comment]
Great, thanks for clarifying!

**Comment by shbhuk** [comment]
@dfm - What is the latest version of pymc3 that you've tested for exoplanet? 
I believe one of the newer ones >3.8 combines the posterior sampling step with the inference part.
See - https://nbviewer.jupyter.org/github/OriolAbril/Exploratory-Analysis-of-Bayesian-Models/blob/multi_obs_ic/content/Section_04/Multiple_likelihoods.ipynb

`    idata = pm.sample(draws=2000, random_seed=1375, return_inferencedata=True)`

**Comment by dfm** [comment]
Exoplanet is tested with 3.8, 3.9 and GitHub master. I'm not sure what you mean about combining posterior sampling and inference (I consider those to mean the same thing), but you can certainly use any pymc3 features you want to!
