### ISSUE TITLE
Docs: Highlighted text after search is hard to read

### ISSUE THREAD

**Issue by adrn** [exoplanet-dev/exoplanet#88]
If I go to the exoplanet docs and search for something, e.g., "impact parameter", the highlighted text on the search results page seems to be nearly white text on white background?

![image](https://user-images.githubusercontent.com/583379/79992441-79f57b00-8481-11ea-9cc5-ca030c6475f1.png)

Google Chrome Version 80.0.3987.163

**Comment by adrn** [comment]
Example: https://docs.exoplanet.codes/en/stable/user/api/?highlight=impact%20parameter

**Comment by dfm** [comment]
Thanks!

This will be fixed by adding some CSS to: https://github.com/exoplanet-dev/exoplanet/blob/master/docs/_static/css/exoplanet.css

or by adding 

```python
html_theme_options = {
    'color': '#SOMECOLOR', 
}
```

to `conf.py`.

**Comment by dfm** [comment]
Fixed!
